# Generated by Django 3.0.6 on 2020-06-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japan', '0002_orderinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='end_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='start_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
